server:
  port: 8001

spring:
    application:
        name: read-write
        
    datasource:
      db1:
        jdbc-url: jdbc:mysql://192.168.56.103:3306/read?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
      db2:
        jdbc-url: jdbc:mysql://192.168.56.103:3306/write?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml